name: farmstuff
version: '1.1'
main: org.farmstuff.farmstuff.Farmstuff
api-version: '1.21'
commands:
  trampling:
    description: disable or enable player trampling
    usage: /trampling [on/off|menu|<player> <on/off>]
    permission: farmstuff.trampling
    permission-message: You don't have permission to use this command.

permissions:
  farmstuff.trampling:
    description: Base trampling command permission
    default: true
  farmstuff.trampling.self:
    description: Allows players to toggle their own trampling settings
    default: true
  farmstuff.trampling.others:
    description: Allows changing other players' trampling settings
    default: op
  farmstuff.trampling.global:
    description: Allows changing global trampling settings
    default: op